name: 📄 Build Report PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Generate report.pdf
        run: node generate-pdf.js

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: training-report
          path: report.pdf
